## Machine Learning Algorithms

### Dependency

In [50]:
import seaborn as sns
import numpy as np
import pandas as pd
import random

from sklearn.model_selection import train_test_split

### Load dataset

In [470]:
iris = sns.load_dataset('iris')

### Variable settings

In [471]:
X = iris.iloc[:, 0:4]
y = iris.iloc[:, 4]

### Divide dataset

In [472]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [49]:
train.groupby(train.species).count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                39           39            39           39
versicolor            37           37            37           37
virginica             29           29            29           29

### 1. K-Nearest Neighbors

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
classfier = KNeighborsClassifier(n_neighbors=5)
classfier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [38]:
y_pred = classfier.predict(x_test)

In [41]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.94      1.00      0.97        15
   virginica       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



### 2. Naive Bayes

In [72]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score

#### Gaussian NB

In [73]:
gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)

In [74]:
print("Number of mislabeled points out of a total %d points : %d"
      % (iris.shape[0],(y_test != y_pred).sum()))

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

Number of mislabeled points out of a total 150 points : 2
[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96


#### Multinomial NB

In [75]:
mnb = MultinomialNB()
y_pred = mnb.fit(x_train, y_train).predict(x_test)

In [76]:
print("Number of mislabeled points out of a total %d points : %d"
      % (iris.shape[0],(y_test != y_pred).sum()))

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

Number of mislabeled points out of a total 150 points : 2
[[19  0  0]
 [ 0 15  0]
 [ 0  2 14]]
0.96


### 3. Logistic Regression

In [85]:
from sklearn.linear_model import LogisticRegression

In [86]:
logis = LogisticRegression()
logis.fit(x_train, y_train)
y_pred = logis.predict(x_test)

C:\ProgramData\Anaconda3\envs\new_ml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\envs\new_ml\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [87]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
1.0


### 4. Decision Tree

In [88]:
from sklearn import tree

In [89]:
dctree = tree.DecisionTreeClassifier()
dctree.fit(x_train, y_train)
y_pred = dctree.predict(x_test)

In [90]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96


### 5. Artificial Neural Network

In [132]:
from keras.layers import *
from keras.models import Sequential
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

In [473]:
x_values = np.array(x_train.values)
x_test_ = np.array(x_test.values)

le = LabelEncoder()
y_values = le.fit_transform(y_train)
y_values = np_utils.to_categorical(y_values)

y_test_ = le.fit_transform(y_test)
y_test_ = np_utils.to_categorical(y_test_)

In [476]:
model = Sequential()

model.add(Dense(16, input_dim=x_values.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_81 (Dense)             (None, 16)                80        
_________________________________________________________________
dense_82 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_83 (Dense)             (None, 3)                 27        
Total params: 243
Trainable params: 243
Non-trainable params: 0
_________________________________________________________________


In [477]:
model.fit(x_values, y_values, batch_size=10, epochs=100)

Epoch 1/100
100/100 [==============================] - 1s 6ms/step - loss: 0.9899 - acc: 0.3500
Epoch 2/100
100/100 [==============================] - 0s 80us/step - loss: 0.9482 - acc: 0.5800
Epoch 3/100
100/100 [==============================] - 0s 100us/step - loss: 0.9361 - acc: 0.6200
Epoch 4/100
100/100 [==============================] - 0s 90us/step - loss: 0.9284 - acc: 0.6300
Epoch 5/100
100/100 [==============================] - 0s 100us/step - loss: 0.9191 - acc: 0.6300
Epoch 6/100
100/100 [==============================] - 0s 100us/step - loss: 0.9108 - acc: 0.6300
Epoch 7/100
100/100 [==============================] - 0s 100us/step - loss: 0.9023 - acc: 0.6400
Epoch 8/100
100/100 [==============================] - 0s 100us/step - loss: 0.8938 - acc: 0.6500
Epoch 9/100
100/100 [==============================] - 0s 90us/step - loss: 0.8881 - acc: 0.6500
Epoch 10/100
100/100 [==============================] - 0s 90us/step - loss: 0.8802 - acc: 0.6500
Epoch 11/100
100/100 [===

100/100 [==============================] - 0s 80us/step - loss: 0.4062 - acc: 0.9800
Epoch 85/100
100/100 [==============================] - 0s 90us/step - loss: 0.3951 - acc: 0.9600
Epoch 86/100
100/100 [==============================] - 0s 90us/step - loss: 0.3940 - acc: 0.9500
Epoch 87/100
100/100 [==============================] - 0s 100us/step - loss: 0.3880 - acc: 0.9700
Epoch 88/100
100/100 [==============================] - 0s 90us/step - loss: 0.3824 - acc: 0.9500
Epoch 89/100
100/100 [==============================] - 0s 110us/step - loss: 0.3790 - acc: 0.9700
Epoch 90/100
100/100 [==============================] - 0s 100us/step - loss: 0.3765 - acc: 0.9600
Epoch 91/100
100/100 [==============================] - 0s 90us/step - loss: 0.3671 - acc: 0.9700
Epoch 92/100
100/100 [==============================] - 0s 90us/step - loss: 0.3664 - acc: 0.9700
Epoch 93/100
100/100 [==============================] - 0s 100us/step - loss: 0.3589 - acc: 0.9700
Epoch 94/100
100/100 [=======

In [480]:
loss, acc = model.evaluate(x_test_, y_test_)
print("[Loss: %.4f, Acc: %.4f]" % (loss, acc))

50/50 [==============================] - 0s 120us/step
[Loss: 0.3324, Acc: 0.9800]


In [483]:
predictions = model.predict(x_test_)

In [491]:
n = random.randint(0, len(x_test_)-1)
print("[Pred: %d, GT: %d]" % (np.argmax(predictions[n]), np.argmax(y_test_[n])))

[Pred: 2, GT: 2]


### 6. Support Vector Machine

In [492]:
from sklearn.svm import SVC

In [493]:
model = SVC(kernel='rbf', C=1e10).fit(x_train, y_train)

C:\ProgramData\Anaconda3\envs\new_ml\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [501]:
y_pred = model.predict(x_test)

In [502]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
0.96


### 7. Random Forest

In [503]:
from sklearn.ensemble import RandomForestClassifier

In [507]:
rf = RandomForestClassifier(n_estimators=500, oob_score=True, random_state=123456)
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=True, random_state=123456,
                       verbose=0, warm_start=False)

In [508]:
y_pred = rf.predict(x_test)

In [509]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred, normalize=True))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
